# Generated by Django 6.0.5 on 2026-05-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclient',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
