# Generated by Django 6.0.5 on 2026-05-21 10:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0003_remove_student_b_form_number_feerecord_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feerecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='feerecord',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='grade',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_type',
            field=models.CharField(default='full', max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolclient',
            name='admin_password',
            field=models.CharField(default='AxisFallback123!', max_length=128),
        ),
        migrations.AlterField(
            model_name='schoolclient',
            name='admin_username',
            field=models.CharField(default='admin_pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='schoolclient',
            name='school_logo',
            field=models.FileField(blank=True, null=True, upload_to='school_logos/'),
        ),
        migrations.AlterField(
            model_name='schoolfeesettings',
            name='due_date_offset',
            field=models.PositiveSmallIntegerField(default=15, help_text='Days after generation when fee is due'),
        ),
        migrations.AlterField(
            model_name='schoolfeesettings',
            name='fee_generation_day',
            field=models.PositiveSmallIntegerField(default=1, help_text='Day of month (1-31)'),
        ),
        migrations.AlterField(
            model_name='schoolfeesettings',
            name='late_fee_penalty',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Penalty %', max_digits=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='student',
            name='custom_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_cnic',
            field=models.CharField(help_text='35202-XXXXXXX-X', max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('graduated', 'Graduated')], default='active', max_length=20),
        ),
    ]
