# Generated by Django 6.0.5 on 2026-05-21 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0004_remove_feerecord_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolfeesettings',
            name='tenant',
        ),
    ]
