# Generated by Django 6.0.5 on 2026-06-01 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0004_add_tenant_type_and_gym_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymattendance',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
