# Generated by Django 4.2.16 on 2026-06-27 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("axis_saas", "0010_add_voucher_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeVoucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.PositiveSmallIntegerField()),
                ("year", models.PositiveSmallIntegerField()),
                ("base_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "custom_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "extra_charges",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("save_charges_for_future", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generated", "Generated"),
                            ("paid_partial", "Partially Paid"),
                            ("paid_full", "Fully Paid"),
                        ],
                        default="generated",
                        max_length=20,
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fee_record",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voucher",
                        to="axis_saas.feerecord",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vouchers",
                        to="axis_saas.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month"],
                "unique_together": {("student", "month", "year")},
            },
        ),
    ]
